// packages/vue/iframe-resizer.vue
<template>
  <iframe ref="iframe" v-bind="$attrs"></iframe>
</template>

<script>
  import connectResizer from '@iframe-resizer/core'
  import acg from 'auto-console-group'

  const EXPAND = 'expanded'
  const COLLAPSE = 'collapsed'

  const esModuleInterop = (mod) =>
    // eslint-disable-next-line no-underscore-dangle
    mod?.__esModule ? mod.default : mod

  // Deal with UMD not converting default exports to named exports
  const createAutoConsoleGroup = esModuleInterop(acg)

  export default {
    name: 'IframeResizer',

    props: {
      license: {
        type: String,
        required: true
      },
      bodyBackground: {
        type: String,
      },
      bodyMargin: {
        type: String,
      },
      bodyPadding: {
        type: String,
      },
      checkOrigin: {
        type: Boolean,
        default: true,
      },
      direction: {
        type: String,
      },
      log: {
        type: [String, Boolean, Number],
        validator: (value) => {
          switch (value) {
            case COLLAPSE:
            case EXPAND:
            case false:
            case true:
            case -1:
              return true
            default:
              return false
          }
        },
        default: undefined,
      },
      inPageLinks: {
        type: Boolean,
      },
      offset: {
        type: Number,
      },
      scrolling: {
        type: Boolean,
      },
      tolerance: {
        type: Number,
      },
      warningTimeout: {
        type: Number,
      },
    },

    mounted() {
      const self = this
      const { iframe } = this.$refs
      const options = {
        ...Object.fromEntries(
          Object
            .entries(this.$props)
            .filter(([key, value]) => value !== undefined)
        ),
        waitForLoad: true,

        onBeforeClose: () => {
          consoleGroup.event('Blocked Close Event')
          consoleGroup.warn('Close method is disabled, use Vue to remove iframe')
          return false
        },
        onReady: (...args) => self.$emit('onReady', ...args),
        onMessage: (...args) => self.$emit('onMessage', ...args),
        onResized: (...args) => self.$emit('onResized', ...args),
      }

      const connectWithOptions = connectResizer(options)
      self.resizer = connectWithOptions(iframe)

      const consoleOptions = {
        label: `vue(${iframe.id})`,
        expand: options.logExpand, // set inside connectResizer
      }

      const consoleGroup = createAutoConsoleGroup(consoleOptions)
      consoleGroup.event('setup')

      if ([COLLAPSE, EXPAND, true].includes(options.log)) {
        consoleGroup.log('Created Vue component')
      }
    },

    beforeUnmount() {
      this.resizer?.disconnect()
    },

    methods: {
      moveToAnchor(anchor) {
        this.resizer?.moveToAnchor(anchor)
      },
      resize() {
        this.resizer?.resize()
      },
      sendMessage(msg, target) {
        this.resizer?.sendMessage(msg, target)
      },
    },
  }

</script>

// packages/svelte/IframeResizer.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy, onMount } from 'svelte'

  import connectResizer from '@iframe-resizer/core'
  import type { IFrameObject } from '@iframe-resizer/core'
  import acg from 'auto-console-group'

  const EXPAND = 'expanded'
  const COLLAPSE = 'collapsed'

  type LogOption = 'expanded' | 'collapsed' | boolean | -1

  const esModuleInterop = (mod: any) =>
    // eslint-disable-next-line no-underscore-dangle
    mod?.__esModule ? mod.default : mod

  // Deal with UMD not converting default exports to named exports
  const createAutoConsoleGroup = esModuleInterop(acg)

  export let license: string
  export let bodyBackground: string | undefined = undefined
  export let bodyMargin: string | undefined = undefined
  export let bodyPadding: string | undefined = undefined
  export let checkOrigin: boolean | undefined = undefined
  export let direction: string | undefined = undefined
  export let log: LogOption | undefined = undefined
  export let inPageLinks: boolean | undefined = undefined
  export let offset: number | undefined = undefined
  export let scrolling: boolean | undefined = undefined
  export let tolerance: number | undefined = undefined
  export let warningTimeout: number | undefined = undefined

  const dispatch = createEventDispatcher()

  let iframe: HTMLIFrameElement
  let resizer: IFrameObject | null = null

  onMount(() => {
    const props: Record<string, any> = {
      license,
      bodyBackground,
      bodyMargin,
      bodyPadding,
      checkOrigin,
      direction,
      log,
      inPageLinks,
      offset,
      scrolling,
      tolerance,
      warningTimeout,
    }

    const options: Record<string, any> = {
      ...Object.fromEntries(
        Object.entries(props).filter(([, value]) => value !== undefined),
      ),
      waitForLoad: true,

      onBeforeClose: () => {
        consoleGroup.event('Blocked Close Event')
        consoleGroup.warn(
          'Close method is disabled, use Svelte to remove iframe',
        )
        return false
      },
      onReady: (...args: any[]) => dispatch('ready', ...args),
      onMessage: (...args: any[]) => dispatch('message', ...args),
      onResized: (...args: any[]) => dispatch('resized', ...args),
    }

    const connectWithOptions = connectResizer(options)
    resizer = connectWithOptions(iframe)

    const consoleOptions = {
      label: `svelte(${iframe.id})`,
      expand: (options as any).logExpand,
    }

    const consoleGroup = createAutoConsoleGroup(consoleOptions)
    consoleGroup.event('setup')

    if ([COLLAPSE, EXPAND, true].includes(options.log as any)) {
      consoleGroup.log('Created Svelte component')
    }
  })

  onDestroy(() => {
    resizer?.disconnect()
  })

  export function moveToAnchor(anchor: string) {
    resizer?.moveToAnchor(anchor)
  }

  export function resize() {
    resizer?.resize()
  }

  export function sendMessage(msg: any, target?: string) {
    resizer?.sendMessage(msg, target)
  }
</script>

<iframe bind:this={iframe} {...$$restProps}></iframe>
