// example/react/src/App.jsx
import { useRef, useState } from 'react'
import IframeResizer from '@iframe-resizer/react'

import MessageData from './message-data.jsx'

import './App.css'

function App() {
  const iframeRef = useRef(null)
  const [messageData, setMessageData] = useState()
  const [show, setShow] = useState(true)

  const onResized = (data) => setMessageData(data)

  const onMessage = (data) => {
    setMessageData(data)
    alert(`Message from frame ${data.iframe.id}: ${data.message}`)
    iframeRef.current.sendMessage('Hello back from the parent page')
  }

  return (
    <>
      <h2>@iframe-resizer/react example</h2>
      <button onClick={() => setShow(!show)}>{show ? 'Hide' : 'Show'}</button>
      {show &&
        <>
          <IframeResizer
            license="GPLv3"
            log
            forwardRef={iframeRef}
            inPageLinks
            onMessage={onMessage}
            onResized={onResized}
            src="child/frame.content.html"
            style={{ width: '100%', height: '100vh' }}
          />
      
          <MessageData data={messageData} />
        </>
      }
    </>
  )
}

export default App

// example/solid/src/App.tsx
import { createSignal, Show } from 'solid-js'
import IframeResizer from '@iframe-resizer/solid'
import type {
  IframeMessageData,
  IframeResizedData,
} from '@iframe-resizer/solid'
import type { IframeResizerMethods } from '@iframe-resizer/solid'

import MessageData from './message-data'

import './App.css'

function App() {
  let iframeApi: IframeResizerMethods | undefined
  const [messageData, setMessageData] = createSignal<IframeResizedData | IframeMessageData>()
  const [show, setShow] = createSignal(true)

  const onResized = (data: IframeResizedData) => setMessageData(data)

  const onMessage = (data: IframeMessageData) => {
    setMessageData(data)
    alert(`Message from frame ${data.iframe.id}: ${data.message}`)
    iframeApi?.sendMessage('Hello back from the parent page')
  }

  return (
    <>
      <h2>@iframe-resizer/solid example</h2>
      <button onClick={() => setShow(!show())}>{show() ? 'Hide' : 'Show'}</button>
      <Show when={show()}>
        <IframeResizer
          license="GPLv3"
          id="myIframe"
          log
          ref={(r) => (iframeApi = r)}
          inPageLinks
          onMessage={onMessage}
          onResized={onResized}
          src="child/frame.content.html"
          style={{ width: '100%', height: '100vh' }}
        />
        <MessageData data={messageData()} />
      </Show>
    </>
  )
}

export default App
