// packages/svelte/IframeResizer.svelte
<script lang="ts">
  import { createEventDispatcher, onDestroy, onMount } from 'svelte'

  import connectResizer from '@iframe-resizer/core'
  import type { IFrameObject } from '@iframe-resizer/core'
  import acg from 'auto-console-group'

  const EXPAND = 'expanded'
  const COLLAPSE = 'collapsed'

  type LogOption = 'expanded' | 'collapsed' | boolean | -1

  const esModuleInterop = (mod: any) =>
    // eslint-disable-next-line no-underscore-dangle
    mod?.__esModule ? mod.default : mod

  // Deal with UMD not converting default exports to named exports
  const createAutoConsoleGroup = esModuleInterop(acg)

  export let license: string
  export let bodyBackground: string | undefined = undefined
  export let bodyMargin: string | undefined = undefined
  export let bodyPadding: string | undefined = undefined
  export let checkOrigin: boolean | undefined = undefined
  export let direction: string | undefined = undefined
  export let log: LogOption | undefined = undefined
  export let inPageLinks: boolean | undefined = undefined
  export let offset: number | undefined = undefined
  export let scrolling: boolean | undefined = undefined
  export let tolerance: number | undefined = undefined
  export let warningTimeout: number | undefined = undefined

  const dispatch = createEventDispatcher()

  let iframe: HTMLIFrameElement
  let resizer: IFrameObject | null = null

  onMount(() => {
    const consoleGroup = createAutoConsoleGroup()

    const props: Record<string, any> = {
      license,
      bodyBackground,
      bodyMargin,
      bodyPadding,
      checkOrigin,
      direction,
      log,
      inPageLinks,
      offset,
      scrolling,
      tolerance,
      warningTimeout,
    }

    const options: Record<string, any> = {
      ...Object.fromEntries(
        Object.entries(props).filter(([, value]) => value !== undefined),
      ),
      waitForLoad: true,

      onBeforeClose: () => {
        consoleGroup.event('Blocked Close Event')
        consoleGroup.warn(
          'Close method is disabled, use Svelte to remove iframe',
        )
        return false
      },
      onReady: (...args: any[]) => dispatch('ready', ...args),
      onMessage: (...args: any[]) => dispatch('message', ...args),
      onResized: (...args: any[]) => dispatch('resized', ...args),
    }

    consoleGroup.label(`svelte(${iframe.id})`)
    consoleGroup.event('setup')

    resizer = connectResizer(options)(iframe)

    consoleGroup.expand(options.logExpand)
    if ([COLLAPSE, EXPAND, true].includes(options.log as any)) {
      consoleGroup.log('Created Svelte component')
    }
  })

  onDestroy(() => {
    resizer?.disconnect()
  })

  export function moveToAnchor(anchor: string) {
    resizer?.moveToAnchor(anchor)
  }

  export function sendMessage(msg: any, target?: string) {
    resizer?.sendMessage(msg, target)
  }
</script>

<iframe bind:this={iframe} {...$$restProps}></iframe>

// packages/solid/IframeResizer.tsx
import connectResizer from '@iframe-resizer/core'
import type {
  IFrameComponent,
  IFrameMessageData,
  IFrameMouseData,
  IFrameObject,
  IFrameResizedData,
  IFrameScrollData,
} from '@iframe-resizer/core'
import acg from 'auto-console-group'
import type { ComponentProps } from 'solid-js'
import { onCleanup, onMount, splitProps } from 'solid-js'

// Deal with UMD not converting default exports to named exports
// eslint-disable-next-line no-underscore-dangle
const esModuleInterop = (mod: any): any => (mod?.__esModule ? mod.default : mod)
const createAutoConsoleGroup = esModuleInterop(acg)

export type IframeResizerMethods = Pick<
  IFrameObject,
  'moveToAnchor' | 'resize' | 'sendMessage'
> & {
  getElement: () => IFrameComponent
}

export type IframeResizerProps = {
  license: string
  bodyBackground?: string | null
  bodyMargin?: string | number | null
  bodyPadding?: string | number | null
  checkOrigin?: boolean | string[]
  direction?: 'vertical' | 'horizontal' | 'none' | 'both'
  inPageLinks?: boolean
  log?: boolean | 'expanded' | 'collapsed'
  offsetSize?: number
  scrolling?: boolean | 'omit'
  tolerance?: number
  waitForLoad?: boolean
  warningTimeout?: number
  onReady?: (iframe: IFrameComponent) => void
  onMessage?: (data: IFrameMessageData) => void
  onResized?: (data: IFrameResizedData) => void
  onScroll?: (data: IFrameScrollData) => boolean
  onMouseEnter?: (data: IFrameMouseData) => void
  onMouseLeave?: (data: IFrameMouseData) => void
  ref?: (methods: IframeResizerMethods) => void
} & Omit<
  ComponentProps<'iframe'>,
  'scrolling' | 'ref' | 'onScroll' | 'onMouseEnter' | 'onMouseLeave'
>

const RESIZER_KEYS = [
  'license',
  'bodyBackground',
  'bodyMargin',
  'bodyPadding',
  'checkOrigin',
  'direction',
  'inPageLinks',
  'log',
  'offsetSize',
  'scrolling',
  'tolerance',
  'waitForLoad',
  'warningTimeout',
  'onReady',
  'onMessage',
  'onResized',
  'onScroll',
  'onMouseEnter',
  'onMouseLeave',
  'ref',
] as const

export default function IframeResizer(props: IframeResizerProps) {
  let iframeEl!: IFrameComponent
  const [local, iframeProps] = splitProps(props, RESIZER_KEYS)
  const consoleGroup = createAutoConsoleGroup()

  onMount(() => {
    const {
      license,
      bodyBackground,
      bodyMargin,
      bodyPadding,
      checkOrigin,
      direction,
      inPageLinks,
      log,
      offsetSize,
      scrolling,
      tolerance,
      waitForLoad,
      warningTimeout,
      onReady,
      onMessage,
      onResized,
      onScroll,
      onMouseEnter,
      onMouseLeave,
      ref: setRef,
    } = local

    consoleGroup.label(`solid(${iframeEl.id})`)
    consoleGroup.event('setup')

    const options: Record<string, any> = {
      ...Object.fromEntries(
        Object.entries({
          license,
          bodyBackground,
          bodyMargin,
          bodyPadding,
          checkOrigin,
          direction,
          inPageLinks,
          log,
          offsetSize,
          scrolling,
          tolerance,
          warningTimeout,
        }).filter(([, v]) => v !== undefined),
      ),
      waitForLoad: waitForLoad ?? true,
      onBeforeClose: () => {
        consoleGroup.warn(
          'Close method is disabled, use Solid to remove the iframe.',
        )
        return false
      },
      onReady,
      onMessage,
      onResized,
      onScroll,
      onMouseEnter,
      onMouseLeave,
    }

    const resizer = connectResizer(options)(iframeEl)

    consoleGroup.expand(log === 'expanded')
    if (log) consoleGroup.log('Created Solid component')

    if (typeof setRef === 'function') {
      setRef({
        getElement: () => iframeEl,
        moveToAnchor: (anchor) => resizer?.moveToAnchor(anchor),
        resize: () => resizer?.resize(),
        sendMessage: (message, targetOrigin) =>
          resizer?.sendMessage(message, targetOrigin),
      })
    }

    onCleanup(() => {
      consoleGroup.endAutoGroup()
      resizer?.disconnect()
    })
  })

  // eslint-disable-next-line jsx-a11y/iframe-has-title
  return <iframe {...iframeProps} ref={iframeEl} />
}
